# .github/workflows/merge_rules.yml

name: Merge Remote Rule Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  merge-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. 检出仓库代码，以便访问 config.yml 和 build.sh
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安装 yq (我们的脚本依赖项)
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version # 验证安装成功

      # 3. 运行构建脚本
      - name: Run Build Script
        run: |
          # 给予脚本执行权限
          chmod +x ./build.sh
          # 执行脚本
          ./build.sh
          
      # 4. 提交所有在 dist/ 目录下的变更
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(bot): Auto-generate rule files from remote sources'
          # 使用通配符来匹配 dist 目录下的所有 .list 文件
          file_pattern: 'dist/*.list'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
